// Puente Micro SaaS — 企画スコアリング基準 v1
// ai-analyzer.ts が system prompt に include する外部 rubric。
// 点数基準・閾値・スコープ外機能・改善提案テンプレを一元化し、
// プロジェクト間・スキル間で再利用できる単一ソースとする。

export const SCORING_RUBRIC_VERSION = 'v1';

export const SCORING_RUBRIC = [
  '# Puente Micro SaaS — 企画スコアリング基準 v1',
  '',
  'Puente Micro SaaS Store に投稿された企画を評価し、自動開発トリガーの可否を判定するための統一基準。',
  '',
  '## 3 軸スコアリング（各 0-100 点）',
  '',
  '各軸ごとに score (整数 0-100) と reason (日本語 50 字程度) を必ず出力する。',
  '',
  '### 1. feasibility — 実現可能性',
  '',
  'プエンテ標準技術スタック（Cloudflare Workers + Supabase + React + Stripe + Claude API）で、3 営業日以内にデプロイ可能な状態に仕上げられるか。',
  '',
  '- 90-100: CRUD + 単純な AI プロンプト 1 本で完結。既存ライブラリ/API だけで組める',
  '- 75-89: 少し工夫いるが 3 日で到達可。API 連携 2-3 個まで',
  '- 60-74: 3 日では厳しいが、スコープ絞れば達成可',
  '- 40-59: カスタム実装が多く 3 日では不可能',
  '- 0-39: 根本的に本プラットフォームで実現困難',
  '',
  '### 2. profitability — 収益性',
  '',
  '国内市場規模 × 課金モデル × 想定 ARPU × 取得しやすさの総合評価。BEP（損益分岐点）達成見込みが指標。',
  '',
  '- 90-100: TAM 100 億円以上、高単価（ARPU 2,000 円以上）、広告不要で自然流入あり',
  '- 75-89: TAM 10 億円以上、ARPU 1,000-2,000 円、コンテンツマーケで獲得可',
  '- 60-74: TAM 1 億円、ARPU 500-1,000 円、獲得にやや工夫要',
  '- 40-59: TAM 1 億円未満、課金転換難しい',
  '- 0-39: 収益化の絵がまったく描けない',
  '',
  '### 3. technical_difficulty — 技術難易度（低いほど高得点）',
  '',
  '実装の複雑度の逆数。シンプル = 高得点。feasibility は「3日で届くか」、technical_difficulty は「保守しやすいか」の長期観点。',
  '',
  '- 90-100: フロント + Supabase CRUD + 単純 AI 呼び出し。バグ起点が最小',
  '- 75-89: リアルタイム通知 / webhook 追加、状態遷移ややあり',
  '- 60-74: 複数サードパーティ API、決済連携、リアルタイム同期',
  '- 40-59: 非同期ジョブキュー、大量データ処理、複雑な RLS',
  '- 0-39: カスタムインフラが要る、スケールに設計が必要',
  '',
  '### total_score 算出',
  '',
  'total_score = floor((feasibility + profitability + technical_difficulty) / 3)',
  '',
  '## 判定閾値',
  '',
  '- total_score ≥ 85 かつ scope_ok=true: auto_dev（自動開発キューに追加）',
  '- 60 ≤ total_score < 85: needs_improvement（改善提案 3-5 個をユーザーに返す）',
  '- total_score < 60: rejected（却下。却下理由も返す）',
  '- scope_ok=false: スコア問わず needs_improvement 以下（スコープ確認を求める）',
  '',
  '## スコープ外機能（必ず scope_ok=false にする）',
  '',
  '- ネイティブモバイルアプリ（iOS / Android）',
  '- ハードウェア / IoT 連携',
  '- ブロックチェーン / 暗号通貨',
  '- 大規模データ処理 / 機械学習モデルのトレーニング',
  '- ビデオ通話 / 音声通話',
  '- Web スクレイピング / クローリング',
  '',
  'これらが企画に含まれる場合は scope_ok=false、out_of_scope_features[] にリストし、alternatives[] に代替案を返す。',
  '',
  '## improvement_suggestions（60-84 または scope_ok=false 時必須）',
  '',
  '3-5 個、各項目は具体的な行動指示。次の視点から出す:',
  '',
  '1. スコア向上: total_score を 85 以上にするには何を絞り込む／追加するか',
  '2. スコープ内化: スコープ外機能の代替案',
  '3. ペルソナ絞り込み: ターゲットを狭めることで profitability 向上',
  '4. 機能削減: P0/P1/P2 の優先度で P2 を削り feasibility 向上',
  '5. 収益モデル提案: 無料 → 月額 980/1,980/2,980 の階段設計',
  '',
  '## 自己改善ループ参考情報（Phase 2 以降）',
  '',
  '将来のフェーズで、以下を system prompt に RAG 注入する:',
  '',
  '- 類似過去事例参照（同カテゴリ / 同 TAM の published SaaS の実績）',
  '- 高パフォーマンス事例: conversion rate >10% / 30day retention >40% / MRR >100k',
  '- 低パフォーマンス事例: 上記を下回るものの構造的パターン',
].join('\n');
